<?php

return [
    [ 'code' => '00', 'name' => 'Por Definir', 'father' => '' ],
    [ 'code' => '01', 'name' => 'Dirección General', 'father' => '' ],
    [ 'code' => '02', 'name' => 'Economía', 'father' => '01' ],
    [ 'code' => '03', 'name' => 'Contabilidad', 'father' => '02' ],
    [ 'code' => '04', 'name' => 'Finanzas', 'father' => '02' ],
    [ 'code' => '05', 'name' => 'Estadísticas', 'father' => '02' ],
    [ 'code' => '06', 'name' => 'Planificación', 'father' => '02' ],
    [ 'code' => '07', 'name' => 'Técnica y Desarrollo', 'father' => '01' ],
    [ 'code' => '08', 'name' => 'Inversiones', 'father' => '07' ],
    [ 'code' => '09', 'name' => 'A.B.T.', 'father' => '01' ],
    [ 'code' => '10', 'name' => 'Auditoría', 'father' => '01' ],
    [ 'code' => '11', 'name' => 'Cuadros', 'father' => '01' ],
    [ 'code' => '12', 'name' => 'Cultivos Varios', 'father' => '01' ],
    [ 'code' => '13', 'name' => 'Energía', 'father' => '01' ],
    [ 'code' => '14', 'name' => 'Informática', 'father' => '01' ],
    [ 'code' => '15', 'name' => 'Jurídicos', 'father' => '01' ],
    [ 'code' => '16', 'name' => 'Organización y Control', 'father' => '01' ],
    [ 'code' => '17', 'name' => 'Producción', 'father' => '01' ],
    [ 'code' => '18', 'name' => 'Puesto de Dirección', 'father' => '01' ],
    [ 'code' => '19', 'name' => 'Recursos Humanos', 'father' => '01' ],
    [ 'code' => '20', 'name' => 'Seguridad y Protección', 'father' => '01' ],
    [ 'code' => '21', 'name' => 'Servicios Internos', 'father' => '01' ],
    [ 'code' => '22', 'name' => 'UEB Aseguramiento', 'father' => '01' ],
    [ 'code' => '23', 'name' => 'UEB Cafetal', 'father' => '01' ],
    [ 'code' => '24', 'name' => 'UEB Calderón', 'father' => '01' ],
    [ 'code' => '25', 'name' => 'UEB Centro Proceso', 'father' => '01' ],
    [ 'code' => '26', 'name' => 'UEB Corojal', 'father' => '01' ],
    [ 'code' => '27', 'name' => 'UEB Despalillo', 'father' => '01' ],
    [ 'code' => '28', 'name' => 'UEB Forestal', 'father' => '01' ],
    [ 'code' => '29', 'name' => 'UEB Granja Urbana', 'father' => '01' ],
    [ 'code' => '30', 'name' => 'UEB Jíbaro', 'father' => '01' ],
    [ 'code' => '31', 'name' => 'UEB Maquinaria', 'father' => '01' ],
    [ 'code' => '32', 'name' => 'UEB Monterrey', 'father' => '01' ],
    [ 'code' => '33', 'name' => 'UEB Pinito', 'father' => '01' ],
    [ 'code' => '34', 'name' => 'UEB Paradero', 'father' => '01' ],
    [ 'code' => '35', 'name' => 'UEB Río Seco', 'father' => '01' ],
    [ 'code' => '36', 'name' => 'UEB Santa Damiana', 'father' => '01' ],
    [ 'code' => '37', 'name' => 'UEB Troncoso', 'father' => '01' ],
    [ 'code' => '38', 'name' => 'UEB UBP Semilla', 'father' => '01' ],
    [ 'code' => '39', 'name' => 'UEB Vívero', 'father' => '01' ]
];
