<?php

return [
    [ 'code' => '01', 'name' => 'CCS 17 De MAYO' ],
    [ 'code' => '02', 'name' => 'CCS 26 De JULIO' ],
    [ 'code' => '03', 'name' => 'CCS 4O Aniversario De La ANAP' ],
    [ 'code' => '04', 'name' => 'CCS Antonio Maceo' ],
    [ 'code' => '05', 'name' => 'CCS Bartolo Rodríguez González' ],
    [ 'code' => '06', 'name' => 'CCS Camilo Cienfuegos' ],
    [ 'code' => '07', 'name' => 'CCS Carlos Marx' ],
    [ 'code' => '08', 'name' => 'CCS Congreso Campesino En Armas' ],
    [ 'code' => '09', 'name' => 'CCS Conrado Benítez' ],
    [ 'code' => '10', 'name' => 'CCS Esteban Ajete' ],
    [ 'code' => '11', 'name' => 'CCS Francisco Blanco' ],
    [ 'code' => '12', 'name' => 'CCS Hermanos Barcón' ],
    [ 'code' => '13', 'name' => 'CCS Hermanos Saíz' ],
    [ 'code' => '14', 'name' => 'CCS Ignacio Agramonte' ],
    [ 'code' => '15', 'name' => 'CCS Isidro De Armas' ],
    [ 'code' => '16', 'name' => 'CCS Isidro García' ],
    [ 'code' => '17', 'name' => 'CCS Jaime Vena' ],
    [ 'code' => '18', 'name' => 'CCS Jesús Menendez' ],
    [ 'code' => '19', 'name' => 'CCS Lenin' ],
    [ 'code' => '20', 'name' => 'CCS Máximo Lugo' ],
    [ 'code' => '21', 'name' => 'CCS Ormani Arenado' ],
    [ 'code' => '22', 'name' => 'CCS Pedro Rodríguez' ],
    [ 'code' => '23', 'name' => 'CCS Rafael Morales' ],
    [ 'code' => '24', 'name' => 'CCS Rigoberto Fuentes' ],
    [ 'code' => '25', 'name' => 'CCS Rupertino Ajete' ],
    [ 'code' => '26', 'name' => 'CCS Tomás León' ],
    [ 'code' => '27', 'name' => 'CCS Tomás Valdés' ],
    [ 'code' => '28', 'name' => 'CCS V Congreso' ],
    [ 'code' => '29', 'name' => 'CPA 10 De Octubre' ],
    [ 'code' => '30', 'name' => 'CPA Bienvenido Rubido' ],
    [ 'code' => '31', 'name' => 'CPA Juan Manuel Márquez' ],
    [ 'code' => '32', 'name' => 'CPA Leonel Abrahantes' ],
    [ 'code' => '33', 'name' => 'CPA Niceto Pérez' ],
    [ 'code' => '34', 'name' => 'Estación Experimental' ],
    [ 'code' => '35', 'name' => 'UBP Semilla' ]
];
